# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://geocomvos.com
title: GeoComvos Ltd
email: geocomvos@gmail.com
author: GeoComvos Ltd
description: > # "Write an awesome description for your new site here. 
  Geocomvos is a technical consultancy specializing in the development,
  deployment of Free and Open Source Software for Geospatial (FOSS4G).
copyright: 'Copyright &copy; 2021 GeoComvos Ltd. All Rights Reserved.'
credits: 'Credits: Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/geocomvos
  - title: github
    url: https://github.com/GeoComvos
  - title: google
    url: mailto:geocomvos@gmail.com
